FROM node:16.8.0
LABEL version='1.0'
LABEL description='This is a docker image of express server side of CMPT 353 project'

# Set the Working Directory the Containers Terminal
WORKDIR /dillon/CMPT353app
# Copy Project Over from this folder to Container folder
COPY . /dillon/CMPT353app/
#install npm dependencies and dev-dependencies
RUN npm install
## expose port
EXPOSE 8080

# Kick start the container with the entrypoint script
ENTRYPOINT ["/dillon/CMPT353app/server_command.sh"]