FROM node:16.8.0
LABEL version='1.0'
LABEL description='This is a docker image of client side of CMPT 353 project'

# Set the Working Directory the Containers Terminal
WORKDIR /dillon/CMPT353client
# Copy Project Over from this folder to Container folder
COPY . /dillon/CMPT353client/
#install npm dependencies and dev-dependencies
RUN npm install
## expose port
EXPOSE 3000

# Kick start the container with the entrypoint script
ENTRYPOINT ["/dillon/CMPT353client/client_command.sh"]
